name: flutter_application_projeto_integrador
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  
  # FIREBASE - Versões atualizadas e compatíveis
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2  # Atualizada
  firebase_database: ^12.0.2  # Atualizada
  connectivity_plus: ^6.0.3
  
  # IMAGENS E PERMISSÕES - Versões atualizadas
  image_picker: ^1.0.7
  permission_handler: ^12.0.1  # Atualizada
  
  # UTILITÁRIOS
  intl: ^0.20.2  # Atualizada
  path_provider: ^2.1.2
  file_picker: ^10.3.3
  
  # GOOGLE APIS (se você realmente precisar)
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Atualizada

flutter:
  uses-material-design: true

  assets:
    - assets/images/