name: flutter_application_projeto_integrador
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  
  # FIREBASE - Versões atualizadas e compatíveis
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0  # Atualizada
  firebase_database: ^10.4.0  # Atualizada
  connectivity_plus: ^5.0.2
  
  # IMAGENS E PERMISSÕES - Versões atualizadas
  image_picker: ^1.0.7
  permission_handler: ^11.3.1  # Atualizada
  
  # UTILITÁRIOS
  intl: ^0.19.0  # Atualizada
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  
  # GOOGLE APIS (se você realmente precisar)
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Atualizada

flutter:
  uses-material-design: true

  assets:
    - assets/images/