name: flutter_application_projeto_integrador
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: any
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.8.3
  file_picker: ^6.1.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Gusta.jpg
    - assets/images/Edu.JPEG
    - assets/images/Graca.jpg
    - assets/images/fundo.jpg
    - assets/images/logo.png
    - assets/images/Lucco.jpg
